version: "3"

networks:
  proxy_nw:

volumes:
    prometheus_data: {}
    grafana_data: {}
    alertgram_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - proxy_nw
    labels:
      org.label-schema.group: "monitoring"


  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - 9093:9093
    networks:
      - proxy_nw
    labels:
      org.label-schema.group: "monitoring"

  alertgram:
    image: slok/alertgram:latest
    container_name: alertgram
    volumes:
      - alertgram_data:/data
    environment:
      telegram.api-token= {{ telegram_api_token }}
      telegram.chat-id= {{ telegram_chat_id}}
    restart: unless-stopped
    ports:
      - 8088:8080
      - 8081:8081
    networks:
      - proxy_nw
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:7.1.1
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER= {{ grafana_username }}
      - GF_SECURITY_ADMIN_PASSWORD= {{ grafana_password }}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - proxy_nw

    labels:
      org.label-schema.group: "monitoring"

  loki:
    image: grafana/loki:master
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config.yml:/etc/loki/local-config.yml
    networks:
      - proxy_nw
    labels:
      org.label-schema.group: "monitoring"
