global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'rustnode'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
{% for host in groups['rustnode'] %}
      - targets: ['{{ host }}:9100']
{% endfor %}

  - job_name: 'statsdexporter'
    scrape_interval: 5s
    static_configs:
{% for host in groups['rustnode'] %}
      - targets: ['{{ host }}:9102']
{% endfor %}

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'loki'
    scrape_interval: 10s
    static_configs:
      - targets: ['loki:3100']
  - job_name: 'promtail'
    scrape_interval: 10s
    static_configs:
      - targets: ['promtail:9080']


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'
