---
node_exporter_version: 0.18.1
node_exporter_binary_local_dir: ""
node_exporter_binary_install_dir: "/usr/local/bin"
node_exporter_web_listen_address: "0.0.0.0:9100"

node_exporter_system_group: "node-exp"
node_exporter_system_user: "{{ node_exporter_system_group }}"

node_exporter_textfile_dir: "/var/lib/node_exporter"

node_exporter_enabled_collectors:
  - systemd
  - textfile:
      directory: "{{ node_exporter_textfile_dir }}"
#  - filesystem:
#      ignored-mount-points: "^/(sys|proc|dev)($|/)"
#      ignored-fs-types: "^(sys|proc|auto)fs$"

node_exporter_disabled_collectors: []

go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
