{
 "title": "TON Node",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Last client applied block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rnode__shards_client_mc_block" }
   ]
  },
  {
   "title": "Last Applied Block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rnode__last_applied_mc_block" }
   ]
  },
  {
   "title": "Time Diff",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rnode__shards_client_mc_block - rnode__last_applied_mc_block"
    }
   ]
  },
  {
   "title": "Q Server queries count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "q_query_count" }
   ]
  },
  {
   "title": "Q Server documents count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "q_doc_count" }
   ]
  },
  {
   "title": "Q Server Start ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "qserver_start" }
   ]
  },
  {
   "title": "Active queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "q_query_active" }
   ]
  },
  {
   "title": "Q Server query time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "q_query_time" }
   ]
  }
 ]
}