{
 "title": "Rustnode logs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "label_values(nodehost)" }
  ]
 },
 "panels": [
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{rustnode=\"$node\"} |= \"ERROR\" != \"WARN\""
    }
   ]
  },
  {
   "title": "Average batch appends sent to ingesters (Loki)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (loki_distributor_ingester_appends_total[1m])"
    }
   ]
  },
  {
   "title": "Loki's stored chunk entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(loki_ingester_chunk_entries_count[5m])"
    }
   ]
  }
 ]
}