{
 "title": "TON Nodes stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(rnode_shards_client_mc_block, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Last client applied block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rnode_shards_client_mc_block{instance=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Last Applied Block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rnode_last_applied_mc_block{instance=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Time Diff",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rnode_timediff{instance=\"$Node\"}"
    }
   ]
  }
 ]
}