---
- name: Create rustvalidator user
  user:
    name: rustvalidator
    create_home: no
    shell: /usr/sbin/nologin
    group: rust
  tags:
   - install
   - upgrade
   - restart

- name: Create config directory
  file:
    path: "{{ item }}"
    state: directory
    owner: rustvalidator
    mode: '0755'
  with_items:
    - "{{ rustvalidator_conf_dir }}"
  tags:
   - install
   - upgrade
   - restart

- name: Install requirements for package install
  package:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-dev
      - virtualenv
    state: present
  tags:
    - install

- name: Install system packages required for pyenv
  package:
    name:
      - gcc
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - make
      - zlib1g-dev
    state: present
  tags:
    - install

- name: "Copy requirements.txt"
  copy:
    src: 'requirements.txt'
    dest: '{{ rustvalidator_conf_dir }}'
  tags:
    - install

- name: Install specified python requirements in indicated
  shell : 'cd {{ rustvalidator_conf_dir }}; pip3 install -r requirements.txt'
  tags:
    - install

- name: Download {{ network }} abhi configs
  get_url:
    url: "{{ item.key }}"
    dest: "{{ rustvalidator_conf_dir }}/{{ item.value }}"
  with_items:
    - { "key": "{{ config_safemultisig_abi }}","value": "SafeMultisigWallet.abi.json" }
    - { "key": "{{ config_abi_elector_url }}","value": "Elector.abi.json" }
  tags:
   - install
   - upgrade
   - restart

- name: Template systemd service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {"src": "env.j2", "dest": "{{ rustvalidator_conf_dir}}/.env"}
    - {"src": "rust-validator.service.j2", "dest": "/etc/systemd/system/rust-validator.service"}
  tags:
   - install
   - upgrade
   - restart
