---
- name: Create rustvalidator user
  user:
    name: rustvalidator
    create_home: no
    shell: /usr/sbin/nologin
  tags:
   - install
   - upgrade
   - restart

- name: Create config directory
  file:
    path: "{{ item }}"
    state: directory
    owner: rustvalidator
    mode: '0755'
  with_items:
    - "{{ rustvalidator_conf_dir }}"
  tags:
   - install
   - upgrade
   - restart

- name: "copy validator.py"
  template:
    src: 'validator.py'
    dest: '{{ rustvalidator_conf_dir }}'
    mode: 0755



- name: Download {{ network }} abhi configs
  get_url:
    url: "{{ item.key }}"
    dest: "{{ rustvalidator_conf_dir }}/{{ item.value }}"
  with_items:
    - { "key": "{{ config_abi_validator_url }}","value": "Validator.abi.json" }
    - { "key": "{{ config_abi_elector_url }}","value": "Elector.abi.json" }
  tags:
   - install
   - upgrade
   - restart

- name: Template systemd service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {"src": "env.j2", "dest": "{{ rustvalidator_conf_dir}}/.env"}
    - {"src": "rust-validator.service.j2", "dest": "/etc/systemd/system/rust-validator.service"}
  tags:
   - install
   - upgrade
   - restart
