---
# tasks file for rustnode
- name: Install tonos-cli and all dependencies
  import_tasks: install.yml

- name: Remove config dir
  import_tasks: cleanup.yml

- name: Start Rust Node Validator
  import_tasks: start.yml
