---

- name: Start remote build
  shell: "{{ scripts_dir }}/scripts/build.sh"
  when: build == true
  tags: install


# TODO Naming 

- name: Install latest node tools
  shell: "{{ scripts_dir }}/scripts/get_release.sh {{ release_file_name }} {{ release_version }} {{ github_token }}"
  when: build == false
  tags: install
