---
- name: Create rustnode user
  user:
    name: rustnode
    create_home: no
    shell: /usr/sbin/nologin
  tags: install

- name: Start remote build
  shell: "{{ scripts_dir }}/scripts/build.sh"
  when: build == true
  tags: install

- name: Install latest node tools
  shell: "{{ scripts_dir }}/scripts/get_release.sh {{ release_version }} {{ git_repo }} {{ github_token }}"
  when: build == false
  tags: install
