---

environment:
  TON_NODE_GITHUB_REPO: "{{ ton_node_github_repo }}"
  TON_NODE_GITHUB_COMMIT_ID: "{{ ton_node_github_commit_id }}"
  TON_NODE_TOOLS_GITHUB_REPO: "{{ ton_node_tools_github_repo }}"
  TON_NODE_TOOLS_GITHUB_COMMIT_ID: "{{ ton_node_tools_github_commit_id }}"
  TONOS_CLI_GITHUB_REPO: "{{ tonos_cli_github_repo }}"
  TONOS_CLI_GITHUB_COMMIT_ID: "{{ tonos_cli_github_commit_id }}"

- name: Create rustnode user
  user:
    name: rustnode
    create_home: no
    shell: /usr/sbin/nologin
    group: rust
  tags:
   - install

- name: Start remote build
  shell: "cd {{ scripts_dir }} && ./build.sh"
  when: build == true
  tags: 
   - install
   - upgrade

- name: Install node tools from repo
  shell: "{{ scripts_dir }}/get_release.sh {{ release_version }} {{ git_repo }} {{ github_token }}"
  when: build == false
  tags: 
   - install
   - upgrade

- name: Keygen for console
  command: keygen
  tags:
   - install
   - reinstall
  register: console

- set_fact:
    console_pub: "{{ console.stdout | from_json | json_query('public') | to_json }}"
  tags:
   - install
   - reinstall

- set_fact:
    console_pvt: "{{ console.stdout | from_json | json_query('private') | to_json }}"
  tags:
   - install
   - reinstall
