---
- name: Stop rust_node
  systemd:
    state: "stopped"
    name: "rust-node"
  tags:
   - upgrade

- name: Create rustnode user
  user:
    name: rustnode
    create_home: no
    shell: /usr/sbin/nologin
  tags:
   - install
   - upgrade
   - restart

- name: Start remote build
  shell: "cd {{ scripts_dir }}/scripts && ./build.sh"
  when: build == true
  tags: 
   - install
   - upgrade

- name: Install node tools from repo
  shell: "{{ scripts_dir }}/scripts/get_release.sh {{ release_version }} {{ git_repo }} {{ github_token }}"
  when: build == false
  tags: 
   - install
   - upgrade

- name: Keygen for console
  command: keygen
  tags:
   - install
   - restart
  register: console

- set_fact:
    console_pub: "{{ console.stdout | from_json | json_query('public') | to_json }}"
  tags:
   - install
   - restart

- set_fact:
    console_pvt: "{{ console.stdout | from_json | json_query('private') | to_json }}"
  tags:
   - install
   - restart
