---
- name: Create rustnode user
  user:
    name: rustnode
    create_home: no
    shell: /usr/sbin/nologin
  tags:
   - install
   - upgrade
   - restart

- name: Start remote build
  shell: "{{ scripts_dir }}/scripts/build.sh"
  when: build == true
  tags: 
   - install
   - upgrade

- name: Install node tools from repo
  shell: "{{ scripts_dir }}/scripts/get_release.sh {{ release_version }} {{ git_repo }} {{ github_token }}"
  when: build == false
  tags: 
   - install
   - upgrade
