---
- name: Create rustnode user
  user:
    name: rustnode
    create_home: no
    shell: /usr/sbin/nologin
  tags:
   - install
   - upgrade
   - restart

- name: Start remote build
  shell: "{{ scripts_dir }}/scripts/build.sh"
  when: build == true
  tags: 
   - install
   - upgrade

- name: Install node tools from repo
  shell: "{{ scripts_dir }}/scripts/get_release.sh {{ release_version }} {{ git_repo }} {{ github_token }}"
  when: build == false
  tags: 
   - install
   - upgrade

- name: Keygen for console
  command: keygen
  tags:
   - install
   - restart
   - debug
  register: console

- set_fact:
    console_pub: "{{ console.stdout | from_json | json_query('public') | to_json }}"
  tags:
   - install
   - restart
   - debug

- set_fact:
    console_pvt: "{{ console.stdout | from_json | json_query('private') | to_json }}"
  tags:
   - install
   - restart
   - debug

- name: Modify console.json
  copy:
    content: "{{ item.key }}"
    dest: "{{ rustnode_conf_dir }}/{{ item.value }}"
  tags:
   - install
   - restart
   - debug
  with_items:
   - { "key": "{{ console_pvt }}","value": "console" }
   - { "key": "{{ console_pub }}","value": "console.pub" }
