---

- name: Create config directory
  file:
    path: "{{ item }}"
    state: directory
    owner: rustnode
    mode: '0755'
  with_items:
    - "{{ rustnode_conf_dir }}"
    - "{{ database_path }}"
  tags:
   - install
   - upgrade
   - restart

- name: Download {{ network }} global config 
  get_url:
    url: "{{ ton_network_global_conf_url }}"
    dest: "{{ rustnode_conf_dir }}/ton-global.config.json"
  tags:
   - install
   - upgrade
   - restart

- name: Template config files and systemd service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {"src": "rust-node.service.j2", "dest": "/etc/systemd/system/rust-node.service"}
    - {"src": "default_config.json.j2", "dest": "{{ rustnode_conf_dir }}/default_config.json"}
    - {"src": "log_cfg.yml.j2", "dest": "{{ rustnode_conf_dir }}/log_cfg.yml"}
  tags:
   - install
   - upgrade
   - restart

- name: Start rust_node
  systemd:
    enabled: yes
    state: "restarted"
    name: "rust-node"
    daemon_reload: yes
  tags:
   - install
   - upgrade
   - restart
