global:
    resolve_timeout: 5m
route:
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 3h
    receiver: telegram
      routes:
      # Only important alerts.
      - match_re:
          severity: ^(critical)$
        receiver: telegram-critical
receivers:
  - name: "telegram"
    webhook_config:
      - url: "http://alertgram:8080/alerts"
- name: telegram-critical
    webhook_configs:
    - url: 'http://alertgram:8080/alerts?chat-id={{ telegram_chat_id }}'
