---
- name: Remove Scripts dir
  file:
    state: absent
    path: "{{ item }}/"
  with_items:
   - "{{ scripts_dir }}"
  tags:
   - upgrade

- name: Create Scripts dir
  file:
    state: directory
    path: "{{ item }}/scripts"
    mode: 0755
    group: rust
  with_items:
   - "{{ scripts_dir }}"
  tags:
   - install
   - upgrade

- name: Copy scripts to remote
  copy:
    src: "{{ item }}"
    dest: "{{ scripts_dir }}/scripts"
    mode: 0755
    group: rust
  with_fileglob:
    - ../scripts/*
  tags: 
    - install
    - upgrade

- name: Install dependencies
  shell: '{{ scripts_dir }}/scripts/install_deps.sh'
  tags: install
