- name: Copy scripts to remote
  copy:
    src: "{{ item }}"
    dest: "{{ scripts_dir }}/scripts"
    mode: 0755
  with_fileglob:
    - ../scripts/*
  tags: install

- name: Install dependencies
  shell: '{{ scripts_dir }}/scripts/install_deps.sh'
  tags: install
