---
- name: Copy config file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: statsd
  with_items:
    - {"src": "statsd-mapping.yaml", "dest": "{{ statsd_conf_dir }}/statsd-mapping.yaml"}
    - {"src": "statsd_exporter.service", "dest": "/etc/systemd/system/statsd_exporter.service"}
  tags: install

- name: Start statsd
  systemd: 
    enabled: yes
    state: "started"
    name: "statsd_exporter"
    daemon_reload: yes
  tags: start
