---
- name: Create statsd user
  user:
    name: statsd
    create_home: no
    shell: /usr/sbin/nologin

- name: Scripts checkout
  git:
    repo: '{{ git_repo_url }}'
    dest: /opt/FreeTON-Rust-Node 

- name: Create config directory
  file: 
    path: "{{ statsd_conf_dir }}"
    state: directory
    owner: statsd
    mode: '0755'

- name: Install statsd
  command: "/opt/FreeTON-Rust-Node/scripts/statsd.sh {{ statsd_version }}"
